baseURL       = '/'
languageCode  = 'en-us'
title         = 'Manitoba Hydro theme site'

[markup.goldmark.renderer]
    hardWraps = true
    unsafe    = true

[security]
	[security.exec]
		allow = ['^go$', '^npx$', '^postcss$', '^babel$']
